"""Add kind column to artifacts

Revision ID: 0b6a58ecc839
Revises: 1f74f3a068dc
Create Date: 2026-08-01 08:48:58.519708+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6a58ecc839'
down_revision: Union[str, None] = '1f74f3a068dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('kind', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_column('artifacts', 'kind')
    # ### end Alembic commands ###
