"""Initial schema

Revision ID: 1f74f3a068dc
Revises: 
Create Date: 2026-07-31 05:48:19.130658+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1f74f3a068dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # `provider_type` is shared across three tables below (configurations,
    # sessions, messages). Autogenerate does not deduplicate ENUM type
    # creation across tables within a single migration — each column's
    # sa.Enum(name='provider_type') would otherwise try to CREATE TYPE
    # again, failing with "type already exists" on the second and third
    # occurrence. Creating it explicitly once here, then referencing it
    # with create_type=False in every column below, avoids that.
    provider_type_enum = postgresql.ENUM(
        'claude', 'openai', 'ollama', name='provider_type'
    )
    provider_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active_provider', postgresql.ENUM('claude', 'openai', 'ollama', name='provider_type', create_type=False), nullable=False),
    sa.Column('default_model', sa.String(length=150), nullable=False),
    sa.Column('temperature', sa.Float(), server_default='0.7', nullable=False),
    sa.Column('rag_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_configurations_active_provider', 'configurations', ['active_provider'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), server_default='New Session', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_provider_used', postgresql.ENUM('claude', 'openai', 'ollama', name='provider_type', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_title', 'sessions', ['title'], unique=False, postgresql_using='btree')
    op.create_index('ix_sessions_updated_at', 'sessions', ['updated_at'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_count >= 0', name='ck_transcripts_chunk_count_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcripts_ingested_at', 'transcripts', ['ingested_at'], unique=False)
    op.create_index('ix_transcripts_title', 'transcripts', ['title'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('essay', 'markdown_doc', 'html_snippet', 'notes', 'summary', name='artifact_type'), nullable=False),
    sa.Column('render_format', sa.Enum('markdown', 'html', name='render_format'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_session_id', 'artifacts', ['session_id'], unique=False)
    op.create_index('ix_artifacts_type', 'artifacts', ['type'], unique=False)
    op.create_index('ix_artifacts_updated_at', 'artifacts', ['updated_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), server_default='markdown', nullable=False),
    sa.Column('provider_used', postgresql.ENUM('claude', 'openai', 'ollama', name='provider_type', create_type=False), nullable=True),
    sa.Column('artifact_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_role', 'messages', ['role'], unique=False)
    op.create_index('ix_messages_session_id', 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_session_id', table_name='messages')
    op.drop_index('ix_messages_role', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_artifacts_updated_at', table_name='artifacts')
    op.drop_index('ix_artifacts_type', table_name='artifacts')
    op.drop_index('ix_artifacts_session_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_transcripts_title', table_name='transcripts')
    op.drop_index('ix_transcripts_ingested_at', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_sessions_updated_at', table_name='sessions')
    op.drop_index('ix_sessions_title', table_name='sessions', postgresql_using='btree')
    op.drop_table('sessions')
    op.drop_index('ix_configurations_active_provider', table_name='configurations')
    op.drop_table('configurations')

    # Drop the shared `provider_type` enum once, now that all three
    # tables that referenced it (configurations, sessions, messages)
    # have been dropped above.
    provider_type_enum = postgresql.ENUM(name='provider_type')
    provider_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###