"""
Message model.

Stores every individual message exchanged within a `Session` — both
user-authored input and assistant-generated responses (and, where
applicable, system messages used to steer the conversation). This
table is the persistent record fulfilling the project requirement
that all conversation history survives beyond a single request/
process lifetime, stored in PostgreSQL rather than only in memory.
"""

import secrets

from sqlalchemy import DateTime, ForeignKey, Index, String, Text
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin
from app.models.enums import MessageRole, ProviderType

__all__ = ["Message", "generate_message_id"]


def generate_message_id() -> str:
    """
    Generates a unique, URL-safe identifier for a new `Message` row.

    Produces IDs in the format `msg_<16 hex chars>`, e.g.
    `msg_84ab7c12e93f4d21`. Follows the same identifier strategy as
    `generate_session_id` (Phase 6.2): a human-readable prefix
    (`msg_`) makes the entity type obvious at a glance in logs, URLs,
    and API payloads, and `secrets.token_hex(8)` draws from the OS's
    cryptographically secure random source to produce a compact,
    dash-free, purely hexadecimal suffix.

    Returns:
        str: A new identifier in the form `msg_<16 hex chars>`.
    """
    return f"msg_{secrets.token_hex(8)}"


class Message(Base, TimestampMixin):
    """
    A single message within a session's conversation history.

    Each row represents one turn in the conversation — authored by
    the end user, generated by an assistant/LLM provider, or issued
    as a system instruction. Messages belong to exactly one `Session`
    and are deleted automatically when their parent session is
    deleted (see the `cascade="all, delete-orphan"` configuration on
    `Session.messages` from Phase 6.2).

    A message may optionally be linked to an `Artifact` it produced
    or references (e.g. an assistant response that generated a
    markdown document) — this link is nullable since most messages
    do not produce a standalone artifact.

    Inherits `created_at` / `updated_at` from `TimestampMixin`; do
    not redefine them here.
    """

    __tablename__ = "messages"

    __table_args__ = (
        # Speeds up the most frequent query pattern: fetching all
        # messages belonging to a given session (e.g. to render a
        # conversation thread).
        Index("ix_messages_session_id", "session_id"),
        # Speeds up ordering messages chronologically within a session,
        # and range queries such as 'messages since X' for pagination
        # or incremental sync.
        Index("ix_messages_created_at", "created_at"),
        # Speeds up filtering by author role, e.g. isolating only
        # assistant responses for analytics, or excluding system
        # messages from a user-facing transcript view.
        Index("ix_messages_role", "role"),
    )

    id: Mapped[str] = mapped_column(
        String(32),
        primary_key=True,
        default=generate_message_id,
        doc="Primary key. Format: msg_<16 hex chars>, e.g. msg_84ab7c12e93f4d21.",
    )

    session_id: Mapped[str] = mapped_column(
        String(32),
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        doc="Foreign key to the parent session this message belongs to.",
    )

    role: Mapped[MessageRole] = mapped_column(
        SQLEnum(
            MessageRole,
            name="message_role",
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=False,
        doc="Who authored this message: user, assistant, or system.",
    )

    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="Full message text content.",
    )

    content_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="markdown",
        server_default="markdown",
        doc=(
            "Render format of `content` (e.g. 'markdown', 'html'). "
            "Defaults to 'markdown'; kept as a plain string rather than "
            "the RenderFormat enum so new formats can be introduced "
            "without a schema migration."
        ),
    )

    provider_used: Mapped[ProviderType | None] = mapped_column(
        SQLEnum(
            ProviderType,
            name="provider_type",
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=True,
        doc=(
            "LLM provider that generated this message, if it was an "
            "assistant response (e.g. claude, openai, ollama). "
            "NULL for user and system messages."
        ),
    )

    artifact_id: Mapped[str | None] = mapped_column(
        String(32),
        ForeignKey("artifacts.id", ondelete="SET NULL"),
        nullable=True,
        doc=(
            "Optional foreign key to an artifact this message produced "
            "or references. NULL for messages with no associated "
            "artifact."
        ),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    session: Mapped["Session"] = relationship(
        "Session",
        back_populates="messages",
        lazy="selectin",
        doc="The parent session this message belongs to.",
    )

    # `Artifact` is referenced via a string forward reference so this
    # module imports cleanly regardless of module load order —
    # SQLAlchemy resolves relationship targets lazily, at mapper
    # configuration time, not at class-definition time, avoiding any
    # circular import between message.py and artifact.py.
    artifact: Mapped["Artifact | None"] = relationship(
        "Artifact",
        back_populates="messages",
        lazy="selectin",
        doc="The artifact this message produced or references, if any.",
    )

    def __repr__(self) -> str:
        """Returns a concise, debug-friendly representation of the message."""
        return (
            f"Message(id={self.id!r}, session_id={self.session_id!r}, "
            f"role={self.role!r})"
        )